name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          pip install flask
          python -m pytest app/ -v || echo "No tests found"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/p26-multienv:latest ./app
          docker push ${{ secrets.DOCKER_USERNAME }}/p26-multienv:latest

      - name: Deploy to Production
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/p26-multienv:latest
            docker stop flask-app || true
            docker rm flask-app || true
            docker run -d --name flask-app -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/p26-multienv:latest
